//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedArbor.Employee.Entities.Concrete.Validators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageValidatorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageValidatorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedArbor.Employee.Entities.Concrete.Validators.MessageValidatorResource", typeof(MessageValidatorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo CompanyID debe ser mayor a cero.
        /// </summary>
        internal static string Rule001 {
            get {
                return ResourceManager.GetString("Rule001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Email no es correcta, debe ser algo como micorreo@midominio.
        /// </summary>
        internal static string Rule002 {
            get {
                return ResourceManager.GetString("Rule002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo UserName no puede ser nulo o vacio.
        /// </summary>
        internal static string Rule003 {
            get {
                return ResourceManager.GetString("Rule003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo PortalID debe ser mayor a cero.
        /// </summary>
        internal static string Rule004 {
            get {
                return ResourceManager.GetString("Rule004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo RoleID debe ser mayor a cero.
        /// </summary>
        internal static string Rule005 {
            get {
                return ResourceManager.GetString("Rule005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo StatusID debe ser mayor a cero.
        /// </summary>
        internal static string Rule006 {
            get {
                return ResourceManager.GetString("Rule006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Password debe tener una longitud mayor a 10 y menor a 100.
        /// </summary>
        internal static string Rule007 {
            get {
                return ResourceManager.GetString("Rule007", resourceCulture);
            }
        }
    }
}
